# Generated by Django 5.1.7 on 2025-03-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0002_qrcode_qrcode_image_alter_qrcode_is_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='back_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='fill_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/logos/'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
